{% set name = "voici-packages" %}
{% set version = "0.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/v/voici_core/voici_core-{{ version }}.tar.gz
    sha256: f870fc362ab08a189ed013b7ddb2b482e83873ad72efe74e82aed33acb7126ae
    folder: voici_core
  - url: https://pypi.io/packages/source/v/voici/voici-{{ version }}.tar.gz
    sha256: 26b16366e4d7327c1df99899c6f44c233f2e212a7c329de5536ff107c7118dfd
    folder: voici

build:
  noarch: python
  number: 0

outputs:
  - name: voici_core
    version: {{ version }}
    build:
      noarch: python
      script: |
        cd voici_core
        python -m pip install . -vv --no-deps --no-build-isolation --ignore-installed --no-index
      entry_points:
        - voici = voici_core.app:main
    requirements:
      host:
        - python >=3.8
        - pip
        - nodejs >=18,<19
        - hatch-jupyter-builder >=0.5.3
        - hatchling >=1.8.1
      run:
        - python >=3.8
        - voila >=0.5.5,<0.6
        - jupyterlite-core >=0.2.0,<0.5.0
    test:
      imports:
        - voici_core
      commands:
        - voici --help

  - name: voici
    version: {{ version }}
    build:
      noarch: python
      script: |
        cd voici
        python -m pip install . -vv --no-deps --no-build-isolation --ignore-installed --no-index
    requirements:
      host:
        - python >=3.8
        - pip
        - hatch-jupyter-builder >=0.5.3
        - hatchling >=1.8.1
      run:
        - python >=3.8
        - voici_core
        - jupyterlite-xeus >=2.0.0,<3
      run_constrained:
        - voici_core ={{ version }}
    test:
      imports:
        - voici
        - jupyterlite_xeus
      commands:
        - voici --help

about:
  home: https://github.com/voila-dashboards/voici
  license: BSD-3-Clause
  license_family: BSD
  license_file: voici/LICENSE
  summary: Voici turns Jupyter notebooks into static web applications
  description: |
    Voici is a tool for generating static dashboards from Jupyter Notebooks.
    It can be used as a drop-in replacement for Voilà and it has the same
    commands and supports most of Voilà's configuration options.

    Unlike Voilà, which renders interactive dashboards using server-side execution,
    Voici uses WebAssembly (Wasm) kernels to render notebooks in the browser,
    making the resulting dashboard entirely self-contained and distributable.
  dev_url: https://github.com/voila-dashboards/voici

extra:
  recipe-maintainers:
    - jtpio
    - trungleduc
    - martinRenou
